name: smartFin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  build_runner: ^2.4.14
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  fpdart: ^1.1.1
  get: ^4.6.6
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.4 # Added for Flutter Intl support

flutter:
  uses-material-design: true
  generate: true # Ensures localization files are generated automatically

  assets:
    - assets/images/animations/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

flutter_intl:
  enabled: true
  class_name: AppLocalizations # Optional: Sets a custom class name
  main_locale: en # Default language
  arb_dir: lib/l10n # Directory for .arb files
  output_dir: lib/generated # Output directory for generated localization files
