// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWiDm2SlBMqK4ZGVk2mFpEE3ZRJ1nXjg',
    appId: '1:620622055371:web:bb74e185edbbda5d04984e',
    messagingSenderId: '620622055371',
    projectId: 'smartfin-ff24d',
    authDomain: 'smartfin-ff24d.firebaseapp.com',
    storageBucket: 'smartfin-ff24d.firebasestorage.app',
    measurementId: 'G-6610RNQLT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlyUxIM5QVchllhXzJSuIb6KreUvsgUkU',
    appId: '1:620622055371:android:06ed66428f000c5e04984e',
    messagingSenderId: '620622055371',
    projectId: 'smartfin-ff24d',
    storageBucket: 'smartfin-ff24d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFB5-5qL1EDgd0F5aGe4I3tGw0jE9YbgI',
    appId: '1:620622055371:ios:1817c0455aefa04504984e',
    messagingSenderId: '620622055371',
    projectId: 'smartfin-ff24d',
    storageBucket: 'smartfin-ff24d.firebasestorage.app',
    iosClientId: '620622055371-i363o9eqdqr2o3s21deseav0k0ru0l23.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnWiDm2SlBMqK4ZGVk2mFpEE3ZRJ1nXjg',
    appId: '1:620622055371:web:065294a46bc3b30f04984e',
    messagingSenderId: '620622055371',
    projectId: 'smartfin-ff24d',
    authDomain: 'smartfin-ff24d.firebaseapp.com',
    storageBucket: 'smartfin-ff24d.firebasestorage.app',
    measurementId: 'G-QLN5L1G75F',
  );
}
